export const SET_PORTFOLIO = 'SET_PORTFOLIO';
export const SET_STOCK_HOLDINGS = 'SET_STOCK_HOLDINGS';
export const SET_CASH_HOLDINGS = 'SET_CASH_HOLDINGS';
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const ADD_STOCK_TRADE = 'ADD_STOCK_TRADE';
export const ADD_CASH_TRADE = 'ADD_CASH_TRADE';
