version: '2'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  web:
    image: klotzandrew/instantstock_web
    command: sh lib/scripts/start_webapp.sh
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      REDIS_URL: redis://redis:6379

  sidekiq:
    image: klotzandrew/instantstock_web
    volumes:
      - .:/myapp
    links:
      - db
      - redis
    command: sh lib/scripts/start_sidekiq.sh
    environment:
      REDIS_URL: redis://redis:6379
