version: '2'
services:
  db:
    image: postgres
    ports:
      - "5432"

  redis:
    image: redis:latest
    ports:
      - "6379"

  web:
    build: ./server
    command: sh lib/scripts/start_webapp.sh
    volumes:
      - ./server:/myapp
    ports:
      - "4000:4000"
    depends_on:
      - db
      - redis
    environment:
      REDIS_URL: redis://redis:6379
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      API_LOCATION: ${API_LOCATION}

  sidekiq:
    build: ./server
    command: sh lib/scripts/start_sidekiq.sh
    volumes:
      - ./server:/myapp
    links:
      - db
      - redis
    environment:
      REDIS_URL: redis://redis:6379

  cron_service:
    build: ./server
    command: sh lib/scripts/start_cron_server_dev.sh
    volumes:
     - ./server:/myapp
    links:
     - db

  web_client:
    build: ./web_client
    command: npm run start
    volumes:
      - ./web_client:/myapp
    ports:
      - "3000:3000"
    links:
      - web
    environment:
      API_LOCATION: ${API_LOCATION}

  nginx_client:
    build: ./nginx_client
    ports:
     - '80:80'
    links:
     - web_client:web_client

  nginx_api:
    build: ./nginx_api
    ports:
     - '81:80'
    links:
     - web:web
