version: '2'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  web:
    build: ./server
    command: sh lib/scripts/start_webapp.sh
    volumes:
      - ./server:/myapp
    ports:
      - "4000:4000"
    depends_on:
      - db
      - redis
    environment:
      REDIS_URL: redis://redis:6379

  sidekiq:
    build: ./server
    volumes:
      - ./server:/myapp
    links:
      - db
      - redis
    command: sh lib/scripts/start_sidekiq.sh
    environment:
      REDIS_URL: redis://redis:6379

  # NOTE: need to start node locally for development
  # https://github.com/docker/compose/issues/184
  web_client:
    build: ./web_client
    command: npm run start
    volumes:
      - ./web_client:/myapp
    ports:
      - "3000:3000"
    links:
      - web
